#! /bin/sh

pgrep -x picom > /dev/null             || picom --experimental-backends &
pgrep -x sxhkd > /dev/null             || sxhkd &

# Restore the screen layout
$HOME/.screenlayout/layout.sh &

# Set the background
$HOME/.fehbg &

# Enable the numlock
numlockx on &

# Set cursor
# See https://tronche.com/gui/x/xlib/appendix/b/
xsetroot -cursor_name left_ptr &

# Start the bar
for m in $(polybar --list-monitors | cut -d":" -f1 | tac); do
  MONITOR=$m polybar -c ~/.config/polybar/config.ini --reload &
done

# Create 10 workspaces per monitors with $monitor_name-$number
for mon in $(bspc query -M --names); do
  bspc monitor $mon -d Desktop

  for i in {1..10}; do
    bspc monitor $mon -a $mon-$i
  done
  
  bspc desktop Desktop --remove
done

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
